version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-name: svelte
  - dependency-name: url-pattern
  ignore:
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.33.0
    - 3.36.0
